### ISSUE TITLE
broken in Fedora 28?

### ISSUE THREAD

**Issue by ousia** [fedora-haskell/pandoc-types#1]
`ghc-pandoc-types` seems to be broken in _Fedora 28_ (according to <https://copr.fedorainfracloud.org/coprs/petersen/ghc-pandoc-types/build/719596/>).

It would be great, if this could be fixed.

**Comment by juhp** [comment]
https://copr.fedorainfracloud.org/coprs/petersen/ghc-pandoc-types/build/780694/
